# Generated by Django 4.1.7 on 2023-05-13 22:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('author', models.CharField(max_length=255)),
                ('public_date', models.DateField()),
                ('page_num', models.PositiveIntegerField(default=None, null=True)),
                ('description', models.CharField(default=None, max_length=2000, null=True)),
                ('image_url', models.CharField(default=None, max_length=600, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book_service.category')),
            ],
        ),
    ]
